Report dangling witness for constraint system
FindoraNetwork/zei pull request #117
Opened 2022-07-27 11:37 UTC by confuseSUN

* **The major changes of this PR**

when inserting a constant gate, the commit code does not remove `witness` from `hashMap`, because it is meaningless to just insert a constant, the constant will participate in the operation of other gates，and it will be removed at that time.

* **The major impacts of this PR**
  - [ ] Impact WASM?
  - [ ] Impact mainnet data compatibility?

* **Extra documentations**

2022-07-27 22:33 UTC, findora-crypto commented
On my way to review.

2022-08-03 00:16 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +                Some(v) => self.witness_backtrace.insert(var, v),
@confuseSUN More information about why for `insert_constant_gate` we choose to keep the witness backtrace for this variable unchanged?

2022-08-03 00:17 UTC, weikengchen requested changes
^ Only need a note on the previous comment.

2022-08-03 01:20 UTC, confuseSUN commented
> ^ Only need a note on the previous comment.

OK，I will add

2022-08-03 17:53 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +    /// record witness backtracking info for checking dangleing witness
```suggestion
    /// record witness backtracking info for checking dangling witness
```

2022-08-03 17:54 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +        //The constant will be removed when participating in other gate operations
```suggestion
        // The constant will be removed when participating in other gate operations
```

2022-08-03 17:57 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +        //so keep it at this time
```suggestion
```

2022-08-03 17:57 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +        //first，save the variable to be removed
```suggestion
```

2022-08-03 17:57 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +        //second, insert when it exists
```suggestion
```

2022-08-03 17:58 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +                Some(v) => self.witness_backtrace.insert(var, v),
Resolved.

2022-08-03 17:58 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +                    panic!("dangling wintness:\n{}", v);
```suggestion
                    panic!("dangling witness:\n{}", v);
```

2022-08-03 17:58 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +    fn test_dangling_wintness_without_panic() {
```suggestion
    fn test_dangling_witness_without_panic() {
```

2022-08-03 17:58 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +    fn test_dangling_wintness_should_panic() {
```suggestion
    fn test_dangling_witness_should_panic() {
```

2022-08-03 17:59 UTC, weikengchen commented on plonk/src/plonk/constraint_system/turbo.rs
> +        //cs.equal(comm_var, h_var)
```suggestion
        // This step is intentionally omitted.
        // cs.equal(comm_var, h_var)
```

2022-08-03 18:01 UTC, findora-crypto commented on plonk/src/plonk/constraint_system/turbo.rs
> +        //
```suggestion
        //
```

2022-08-03 18:01 UTC, findora-crypto commented on plonk/src/plonk/constraint_system/turbo.rs
> +        // Therefore, here we save the backtrace information,  so that `finish_new_gate` does not
```suggestion
        // Therefore, here we save the backtrace information,  so that `finish_new_gate` does not
```

2022-08-04 00:30 UTC, merged