A mofication in asset_mixing function from circuit.rs was made to avo…
FindoraNetwork/zei pull request #27
Opened 2022-03-10 22:06 UTC by Serge-Juarez

This is subtil modification motivated by the following note in the comments about "asset_mixing"

/// Enforce asset_mixing_with_fees constraints:
/// Inputs = [(type_in_1, v_in_1), ..., (type_in_n, v_in_n)], values {v_in_i} are guaranteed to be positive.
/// Outputs = [(type_out_1, v_out_1), ..., (type_out_m, v_out_m)], values {v_out_j} are guaranteed to be positive.
/// Fee parameters = fee_type and fee_calculating func
///
/// Goal:
/// - Prove that for every asset type except fee_type, the corresponding inputs sum equals the corresponding outputs sum.
/// - Prove that for every asset type that equals fee_type, the inputs sum = the outputs sum + fee
/// - Prove that at least one input is of type fee_type
///
/// The circuit:
/// 1. Compute [sum_in_1, ..., sum_in_n] from inputs, where sum_in_i = \sum_{j : type_in_j == type_in_i} v_in_j

/// Note: If there are two inputs with the same asset type, then their sum_in_i would be the same. <======This one

/// 2. Similarly, compute [sum_out_1, ..., sum_out_m] from outputs.
/// 3. Enumerate pair (i \in [n], j \in [m]), check that:
/// (type_in_i == fee_type) \lor (type_in_i != type_out_j) \lor (sum_in_i == sum_out_j)
/// (type_in_i != fee_type) \lor (type_in_i != type_out_j) \lor (sum_in_i == sum_out_j + fee)
/// 4. Ensure that except the fee type, all the input type has also shown up as an output type.
/// 5. Ensure that for the fee type, if there is no output fee type, then the input must provide the exact fee.
///
/// This function assumes that the inputs and outputs have been correctly bounded.

So instead of having a repited entries it is checked if the "asset type" exists in a hashset, and get rid of repited entries

Please check the code and I give me your thoghts and comments.

2022-03-11 18:47 UTC, harshadptl approved these changes

2022-03-12 06:50 UTC, findora-crypto commented
I disagree with this PR, and feel that it might be introducing a security vulnerability.

Can you explain more why this PR is necessary? I will put a hold on this PR. Would be happy to hop on a call.

2022-03-12 06:51 UTC, findora-crypto requested changes
Unless there is a very specific reason that this is necessary and correct, I oppose this PR.

2022-03-14 05:57 UTC, harshadptl commented
It is some optimization Sergio made to avoid multiple checks for inputs and outputs of same Asset Type.

2022-03-14 07:30 UTC, findora-crypto commented
The problem is here: since each asset type is allocated as a new variable in the circuit, even if the asset types are the same, they have different variable indices. And therefore, I don't think this optimization can actually solve the problem of repeated entries (it can only solve them if they are independent of the actual transfer, which is unlikely to be the case).

2022-03-14 07:31 UTC, findora-crypto commented
And if this is not the performance bottleneck of anonymous transfer, I am leaning toward not doing this optimization.

2022-03-14 18:37 UTC, closed without merging